# The bot always updates the labels, add/remove as necessary [default: false]
alwaysReplace: false
# Treats the text and labels as case sensitive [default: true]
caseSensitive: true
# Array of labels to be applied to the PR [default: []]
customLabels:
  # Conventional commit patterns
  - text: 'feat'       # Akan cocok dengan "feat" di judul/body PR
    label: 'feature'
  - text: 'fix'        # Akan cocok dengan "fix"
    label: 'bug'
  - text: 'chore'      # Akan cocok dengan "chore"
    label: 'improvement'
  - text: 'docs'       # Akan cocok dengan "docs"
    label: 'documentation'
  - text: 'test'       # Akan cocok dengan "test"
    label: 'test'
  - text: 'refactor'   # Akan cocok dengan "refactor"
    label: 'refactored'
# Search the body of the PR for the `text` [default: true]
searchBody: true
# Search the title of the PR for the `text` [default: true]
searchTitle: true
# Search for whole words only [default: false]
wholeWords: false