name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: true
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
		- uses: akhilmhdh/contributors-readme-action@v2.3.10
		  env:
		      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
 
    - name: Check and install dependencies
      run: |
        if [ ! -f package-lock.json ]; then
          echo "::warning::Lockfile not found. Generating new one..."
          npm install --package-lock-only
          
          git config --global user.email "hub@erdev.biz.id"
          git config --global user.name "ErBots"
          
          git add package-lock.json
          git commit -m "chore: add lockfile [skip ci]"
          git push
        fi
        
        npm i
        
        npm ci
 
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Upload coverage
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        flags: unittests