name: Release

on:
  push:
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "::warning::Lockfile tidak ada. Membuat yang baru..."
            pnpm install --no-frozen-lockfile
      
            git config --global user.email "hub@erdev.biz.id"
            git config --global user.name "ErBots"
      
            git add pnpm-lock.yaml
            git commit -m "chore: add lockfile [skip ci]"
            git push
          fi
      
          pnpm install --frozen-lockfile

      - name: Validate package.json
        run: |
          jq empty package.json \
            && echo "✅ package.json valid" \
            || (echo "❌ Invalid package.json" && exit 1)

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Publish to NPM
        run: |
          pnpm publish --access public --no-git-checks
      
          CURRENT_VERSION=$(jq -r .version package.json)
          PACKAGE_NAME=$(jq -r .name package.json)
          
          npm deprecate "${PACKAGE_NAME}@<${CURRENT_VERSION}" "This version is deprecated. Please upgrade to ${CURRENT_VERSION}."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
