name: 'Verify Package Exports'

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    name: 'Test CJS and ESM Exports'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build Package'
        run: npm run build
        
      - name: 'Run CommonJS (require) Test'
        run: node integration-tests/cjs.test.js
        
      - name: 'Run ES Modules (import) Test'
        run: node integration-tests/esm.test.mjs